### ISSUE TITLE
ERROR on GDS_SetConfiguration

### ISSUE THREAD

**Issue by vammendez** [labstreaminglayer/App-g.Tec#8]
Hello,

I had this problem using this app on my g.HIamp, when I put a sampling frequency higher than 1200Hz I obtained this error:

"ERROR on GDS_SetConfiguration : Couldn't set configuration for device 'HA-2015.08.05'. 
The specified sampling rate (2400 Hz) does not support a value of 8 for the number of scans parameter."

I am using the new gNEEDaccess Client API that g.tec is selling now but I could build the app without any problem.

It seems that the solution of this error is to add a lign in the file:  gHIamp_dlg.cpp

in the function that send the configuration (lign 392): void GHIampDlg::accept()

dev_cfg->NumberOfScans = 128; 

and it works. 

I understand that it is a really quick fix for my specific case this is why I put this as an issue for you to know.

The struct GDS_GHIAMP_CONFIGURATION  has a field which is called NumberOfScans and the recommended value depends on the sampling rate. (It can be found in the documentation of gNEEDaccess - Client API).

**Comment by cboulay** [comment]
Thanks for the report.

Hmm... I didn't seem to anticipate needing to change the NumberOfScans. Sorry about this oversight. 

I think what I'll do is add a dropdown box to allow the user to select the number of scans, but upon changing the sampling rate the field will automatically be updated with the recommended number.

Unfortunately I won't have time to fix it this week, but it seems like you aren't blocked by this right now so there is no hurry. Is that correct?

**Comment by vammendez** [comment]
Yes I fixed the problem for my specific case. Thank you.
